const video=document.getElementById('preview'),canvas=document.getElementById('overlay'),ctx=canvas.getContext('2d');
const statusEl=document.getElementById('status'),recBadge=document.getElementById('recBadge'),recordings=document.getElementById('recordings'),startBtn=document.getElementById('start'),stopBtn=document.getElementById('stop'),graceInput=document.getElementById('grace');
let stream,recorder,chunks=[],model,running=false,recording=false,stopTimer=null,lastVideoTime=-1,recordingStartedAt=0;
const setStatus=s=>statusEl.textContent=s;
async function startCamera(){if(running)return;try{stream=await navigator.mediaDevices.getUserMedia({video:{facingMode:{ideal:'environment'},width:{ideal:1280},height:{ideal:720}},audio:true});video.srcObject=stream;await video.play();running=true;startBtn.disabled=true;stopBtn.disabled=false;setStatus('Kamera läuft – KI wird geladen…');model=await cocoSsd.load();setStatus('Bereit – Personen werden erkannt');detectLoop()}catch(e){console.error(e);setStatus('Kamera konnte nicht gestartet werden');alert('Bitte erlaube Kamera und Mikrofon. Die Seite muss normalerweise über HTTPS oder localhost laufen.')}}
function stopCamera(){running=false;clearTimeout(stopTimer);stopTimer=null;if(recording)stopRecording('Manuell gestoppt');stream?.getTracks().forEach(t=>t.stop());stream=null;video.srcObject=null;ctx.clearRect(0,0,canvas.width,canvas.height);startBtn.disabled=false;stopBtn.disabled=true;setStatus('Gestoppt')}
async function detectLoop(){if(!running||!model)return;if(video.readyState>=2&&video.currentTime!==lastVideoTime){lastVideoTime=video.currentTime;const predictions=await model.detect(video);drawBoxes(predictions);const personFound=predictions.some(p=>p.class==='person'&&p.score>=.55);if(personFound){clearTimeout(stopTimer);stopTimer=null;if(!recording)startRecording()}else if(recording&&!stopTimer){const seconds=Math.max(1,Math.min(30,Number(graceInput.value)||4));setStatus(`Keine Person – Stopp in ${seconds}s`);stopTimer=setTimeout(()=>{stopTimer=null;if(recording)stopRecording('Person nicht mehr erkannt')},seconds*1000)}}requestAnimationFrame(detectLoop)}
function drawBoxes(predictions){const vw=video.videoWidth||1280,vh=video.videoHeight||720;canvas.width=vw;canvas.height=vh;ctx.clearRect(0,0,vw,vh);for(const p of predictions.filter(p=>p.class==='person'&&p.score>=.55)){const[x,y,w,h]=p.bbox,line=Math.max(4,vw/320),c=Math.min(w,h)*.18;ctx.save();ctx.strokeStyle='#00ff66';ctx.lineWidth=line;ctx.shadowColor='#00ff66';ctx.shadowBlur=12;ctx.beginPath();ctx.moveTo(x,y+c);ctx.lineTo(x,y);ctx.lineTo(x+c,y);ctx.moveTo(x+w-c,y);ctx.lineTo(x+w,y);ctx.lineTo(x+w,y+c);ctx.moveTo(x,y+h-c);ctx.lineTo(x,y+h);ctx.lineTo(x+c,y+h);ctx.moveTo(x+w-c,y+h);ctx.lineTo(x+w,y+h);ctx.lineTo(x+w,y+h-c);ctx.stroke();ctx.restore();ctx.fillStyle='#00ff66';ctx.font=`700 ${Math.max(15,vw/75)}px system-ui`;ctx.fillText('PERSON',x+8,Math.max(20,y-10));ctx.font=`600 ${Math.max(11,vw/110)}px system-ui`;ctx.fillText(`${Math.round(p.score*100)}%`,x+w-42,y+h-8)}}
function startRecording(){if(!stream||recording)return;chunks=[];const mime=['video/webm;codecs=vp9,opus','video/webm;codecs=vp8,opus','video/webm'].find(MediaRecorder.isTypeSupported);if(!mime){setStatus('Dieser Browser unterstützt keine passende Videoaufnahme.');return}recorder=new MediaRecorder(stream,{mimeType:mime});recorder.ondataavailable=e=>{if(e.data.size)chunks.push(e.data)};recorder.onstop=saveRecording;recorder.start(250);recording=true;recordingStartedAt=Date.now();recBadge.style.display='block';setStatus('● REC – Person erkannt')}
function stopRecording(reason='Aufnahme beendet'){clearTimeout(stopTimer);stopTimer=null;if(!recorder||recorder.state==='inactive')return;recorder.stop();recording=false;recBadge.style.display='none';setStatus(reason)}
function saveRecording(){const blob=new Blob(chunks,{type:recorder?.mimeType||'video/webm'});if(blob.size<1000)return;const url=URL.createObjectURL(blob),time=new Date().toLocaleString('de-DE'),duration=Math.max(0,Math.round((Date.now()-recordingStartedAt)/1000));const item=document.createElement('div');item.className='item';const a=document.createElement('a');a.href=url;a.download=`personcam-${Date.now()}.webm`;a.textContent=`Aufnahme ${time} · ${duration}s – speichern`;item.appendChild(a);recordings.prepend(item);setStatus('Aufnahme fertig – bereit zum Speichern');chunks=[]}
startBtn.addEventListener('click',startCamera);stopBtn.addEventListener('click',stopCamera);window.addEventListener('beforeunload',()=>stream?.getTracks().forEach(t=>t.stop()));